create table retail (
	InvoiceNo Varchar(100),
    StockCode Varchar(100),
    Description TEXT,
    Quantity int,
    InvoiceDate datetime,
    UnitPrice decimal(10,2),
	CustomerID VARCHAR(100),
    Country text);
    
SELECT * FROM retail LIMIT 10;

SELECT MAX(InvoiceDate), MIN(InvoiceDate) FROM retail;

SELECT COUNT(*) FROM retail;

SELECT COUNT(DISTINCT InvoiceNo) FROM retail;
SELECT COUNT(DISTINCT CustomerID) FROM retail;

select 
	round(sum(Quantity*UnitPrice),2) as Total_Revenue
from retail;

# Monthly revenue trend
select
	date_format(InvoiceDate, '%Y-%m') as Month,
	round(sum(Quantity*UnitPrice),2) as Revenue
from retail
group by Month
order by Month;
#Comparatively lower revenue in Dec to April
# Uptrend is observed from May 
# Significant surge in Sep to Nov due to Holiday shopping 
# Highest revenue in Nov cz of Sales, and peak Christmas shopping period


#Top selling products
select
	Description,
    sum(Quantity) as Total_units_sold,
    round(sum(Quantity*UnitPrice), 2) as Revenue,
    round(
		sum(Quantity*UnitPrice)/
        (select sum(Quantity*UnitPrice) from retail) * 100,
	2) as revenue_share_percent
from retail
group by Description
order by Revenue desc
limit 10;


SELECT 
    ROUND(SUM(Revenue), 2) AS top_10_revenue,
    ROUND(
        SUM(Revenue) / 
        (SELECT SUM(Quantity * UnitPrice) FROM retail) * 100, 
    2) AS top_10_revenue_share
FROM (
    SELECT 
        SUM(Quantity * UnitPrice) AS revenue
    FROM retail
    GROUP BY Description
    ORDER BY revenue DESC
    LIMIT 10
) top_products;
# The total revenue generated by the top 10 best-selling products is £679,022.59 which accounts for 8.18% of the total share of revenue. 

